version: 4.0.2.{build}

shallow_clone: true
clone_depth: 1

configuration:
#- MinSizeRel  // https://bugzilla.libsdl.org/show_bug.cgi?id=4233
- Release
- Debug

environment:
  DIST_DIR: '%APPVEYOR_BUILD_FOLDER%\dist'
  CMAKE_DIST_DIR: C:/projects/pdcurses/dist
  WATCOM: C:\Tools\watcom

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      TOOLCHAIN: Watcom
      ARCHIVE: VS2015_%CONFIGURATION%_DOS16_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'Watcom WMake'
      CMAKE_TOOLCHAIN_ARGS: '-DCMAKE_TOOLCHAIN_FILE=..\cmake\watcom_open_dos16_toolchain.cmake'
      CMAKE_ARGS: '-DPDC_DOS_BUILD=ON -DPDC_BUILD_SHARED=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      TOOLCHAIN: Watcom
      ARCHIVE: VS2015_%CONFIGURATION%_DOS32_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'Watcom WMake'
      CMAKE_TOOLCHAIN_ARGS: '-DCMAKE_TOOLCHAIN_FILE=..\cmake\watcom_open_dos32_toolchain.cmake'
      CMAKE_ARGS: '-DPDC_DOS_BUILD=ON -DPDC_BUILD_SHARED=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64_x86
      ARCHIVE: VS2015_%CONFIGURATION%_WIDE_x86_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64_x86
      ARCHIVE: VS2015_%CONFIGURATION%_UTF8_x86_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64
      ARCHIVE: VS2015_%CONFIGURATION%_WIDE_x64_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64
      ARCHIVE: VS2015_%CONFIGURATION%_UTF8_x64_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64_arm
      ARCHIVE: VS2015_%CONFIGURATION%_WIDE_ARM_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64_arm
      ARCHIVE: VS2015_%CONFIGURATION%_UTF8_ARM_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'


    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm.bat'
      ARCHITECTURE: amd64_arm
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_ARM_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm.bat'
      ARCHITECTURE: amd64_arm
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_ARM_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat'
      ARCHITECTURE: amd64_arm64
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_ARM64_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat'
      ARCHITECTURE: amd64_arm64
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_ARM64_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat'
      ARCHITECTURE: amd64_x86
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_x86_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat'
      ARCHITECTURE: amd64_x86
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_x86_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat'
      ARCHITECTURE: amd64
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_x64_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat'
      ARCHITECTURE: amd64
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_x64_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'

init:
  - echo BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%

install:

  # Open Watcom
  - if "%TOOLCHAIN%"=="Watcom" ( echo Installing Open Watcom )
  - if "%TOOLCHAIN%"=="Watcom" ( cd %APPVEYOR_BUILD_FOLDER% )
  - if "%TOOLCHAIN%"=="Watcom" ( set "OPEN_WATCOM_URL=https://sourceforge.net/projects/openwatcom/files/open-watcom-1.9/open-watcom-c-win32-1.9.exe" )
  - if "%TOOLCHAIN%"=="Watcom" ( appveyor DownloadFile "%OPEN_WATCOM_URL%" -FileName open-watcom-c-win32-1.9.exe )
  - if "%TOOLCHAIN%"=="Watcom" ( 7z x -y open-watcom-c-win32-1.9.exe -o"%WATCOM%" > nul )
  - if "%TOOLCHAIN%"=="Watcom" ( set "PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%" )
  - if "%TOOLCHAIN%"=="Watcom" ( set "EDPATH=%WATCOM%\EDDAT" )
  - if "%TOOLCHAIN%"=="Watcom" ( set "INCLUDE=%WATCOM%\H;%WATCOM%\H\NT" )

  - cmake --version

build:
  parallel: true

build_script:

  - if exist "%VCVARSALL%" ( call "%VCVARSALL%" %ARCHITECTURE% )

  - if "%CONFIGURATION%"=="Debug" ( set PDCDEBUG=ON ) else ( set PDCDEBUG=OFF )
  - if "%CONFIGURATION%"=="Debug" ( set PDCDEBUG=ON ) else ( set PDCDEBUG=OFF )

  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build

  - cmake %CMAKE_TOOLCHAIN_ARGS% -G"%GENERATOR%" -DCMAKE_VERBOSE_MAKEFILE=TRUE
          -DCMAKE_BUILD_TYPE=%CONFIGURATION% 
          -DCMAKE_INSTALL_PREFIX="%CMAKE_DIST_DIR%/%APPVEYOR_BUILD_WORKER_IMAGE%"
          -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% -DPDCDEBUG=%PDCDEBUG% %CMAKE_ARGS%
          ..

    cmake --build . --config %CONFIGURATION% --target install

after_build:
  - cd %DIST_DIR%
  - 7z a -tzip %ARCHIVE%.zip "%APPVEYOR_BUILD_WORKER_IMAGE%"
  - certutil -hashfile %ARCHIVE%.zip MD5 > %ARCHIVE%.md5

artifacts:
  - path: dist\$(ARCHIVE).zip
  - path: dist\$(ARCHIVE).md5
