version: 4.0.2.{build}

shallow_clone: true
clone_depth: 1

configuration:
#- MinSizeRel  // https://bugzilla.libsdl.org/show_bug.cgi?id=4233
- Release
- Debug

environment:
  DIST_DIR: '%APPVEYOR_BUILD_FOLDER%\dist'
  WATCOM: C:\Tools\watcom

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      TOOLCHAIN: Watcom20
      TARGET: os2
      GENERATOR: 'Watcom WMake'
      CMAKE_ARGS: '-DPDC_OS2_BUILD=ON -DPDC_BUILD_SHARED=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      CMAKE_TOOLCHAIN_ARGS: '-DCMAKE_TOOLCHAIN_FILE=..\cmake\watcom_open_os2v2_toolchain.cmake'
      ARCHIVE: WATCOM20_%CONFIGURATION%_OS2V2_%APPVEYOR_BUILD_NUMBER%

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      TOOLCHAIN: Watcom19
      TARGET: dos
      GENERATOR: 'Watcom WMake'
      CMAKE_ARGS: '-DPDC_DOS_BUILD=ON -DPDC_BUILD_SHARED=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      CMAKE_TOOLCHAIN_ARGS: '-DCMAKE_TOOLCHAIN_FILE=..\cmake\watcom_open_dos16_toolchain.cmake'
      ARCHIVE: WATCOM19_%CONFIGURATION%_DOS16_%APPVEYOR_BUILD_NUMBER%

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      TOOLCHAIN: Watcom19
      TARGET: dos
      GENERATOR: 'Watcom WMake'
      CMAKE_ARGS: '-DPDC_DOS_BUILD=ON -DPDC_BUILD_SHARED=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      CMAKE_TOOLCHAIN_ARGS: '-DCMAKE_TOOLCHAIN_FILE=..\cmake\watcom_open_dos32_toolchain.cmake'
      ARCHIVE: WATCOM19_%CONFIGURATION%_DOS32_%APPVEYOR_BUILD_NUMBER%

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      TOOLCHAIN: Watcom20
      TARGET: dos
      GENERATOR: 'Watcom WMake'
      CMAKE_ARGS: '-DPDC_DOS_BUILD=ON -DPDC_BUILD_SHARED=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      CMAKE_TOOLCHAIN_ARGS: '-DCMAKE_TOOLCHAIN_FILE=..\cmake\watcom_open_dos16_toolchain.cmake'
      ARCHIVE: WATCOM20_%CONFIGURATION%_DOS16_%APPVEYOR_BUILD_NUMBER%

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      TOOLCHAIN: Watcom20
      TARGET: dos
      GENERATOR: 'Watcom WMake'
      CMAKE_ARGS: '-DPDC_DOS_BUILD=ON -DPDC_BUILD_SHARED=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      CMAKE_TOOLCHAIN_ARGS: '-DCMAKE_TOOLCHAIN_FILE=..\cmake\watcom_open_dos32_toolchain.cmake'
      ARCHIVE: WATCOM20_%CONFIGURATION%_DOS32_%APPVEYOR_BUILD_NUMBER%

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      ARCHITECTURE: amd64_x86
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'
      ARCHIVE: VS2015_%CONFIGURATION%_WIDE_x86_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      ARCHITECTURE: amd64_x86
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'
      ARCHIVE: VS2015_%CONFIGURATION%_UTF8_x86_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      ARCHITECTURE: amd64
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'
      ARCHIVE: VS2015_%CONFIGURATION%_WIDE_x64_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      ARCHITECTURE: amd64
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'
      ARCHIVE: VS2015_%CONFIGURATION%_UTF8_x64_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      ARCHITECTURE: amd64_arm
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      ARCHIVE: VS2015_%CONFIGURATION%_WIDE_ARM_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      ARCHITECTURE: amd64_arm
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      ARCHIVE: VS2015_%CONFIGURATION%_UTF8_ARM_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      ARCHITECTURE: amd64_arm
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_ARM_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      ARCHITECTURE: amd64_arm
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_ARM_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      ARCHITECTURE: amd64_arm64
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_ARM64_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      ARCHITECTURE: amd64_arm64
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=OFF -DPDC_SDL2_DEPS_BUILD=OFF'
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_ARM64_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      ARCHITECTURE: amd64_x86
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_x86_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      ARCHITECTURE: amd64_x86
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_x86_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      ARCHITECTURE: amd64
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=ON -DPDC_UTF8=OFF -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_x64_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat'

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      ARCHITECTURE: amd64
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: '-DPDC_WIDE=OFF -DPDC_UTF8=ON -DPDC_SDL2_BUILD=ON -DPDC_SDL2_DEPS_BUILD=ON'
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_x64_%APPVEYOR_BUILD_NUMBER%
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat'

init:
  - echo BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
  # curl defaults --keepalive-time 60 --max-time ?? about 10 minutes --connect-timeout ??
  - set CURL_ARGS=--location --fail --show-error --keepalive-time 30 --connect-timeout 20 --max-time 300
  - rem Open Watcom install artifacts information
  - if "%TOOLCHAIN%"=="Watcom19" set "ARTIFACT_NAME=open-watcom-c-win32-1.9.exe"
  - if "%TOOLCHAIN%"=="Watcom19" set "ARTIFACT_URL=https://sourceforge.net/projects/openwatcom/files/open-watcom-1.9/%ARTIFACT_NAME%"
  - if "%TOOLCHAIN%"=="Watcom20" set "ARTIFACT_NAME=open-watcom-2_0-c-win-x64.exe"
  - if "%TOOLCHAIN%"=="Watcom20" set "ARTIFACT_URL=https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/%ARTIFACT_NAME%"


install:

  # Open Watcom
  - if "%TOOLCHAIN%"=="Watcom19" ( 
      echo Installing Open Watcom 1.9 &&
      curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%" &&
      7z x -y "%TEMP%\%ARTIFACT_NAME%" -o"%WATCOM%" &&
      set "PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%"
    )
  - if "%TOOLCHAIN%"=="Watcom20" ( 
      echo Installing Open Watcom 2.0 &&
      curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%" &&
      7z x -y "%TEMP%\%ARTIFACT_NAME%" -o"%WATCOM%" &&
      set "PATH=%WATCOM%\BINNT64;%WATCOM%\BINW;%PATH%" 
    )
  - cmake --version

build:
  parallel: true

before_build:

  - if exist "%VCVARSALL%" (
      call "%VCVARSALL%" %ARCHITECTURE%
    )

  - if "%TARGET%"=="dos" (
      set "INCLUDE=%WATCOM%\H"
    )
  - if "%TARGET%"=="os2" (
      set "BEGINLIBPATH=%WATCOM%\BINP\DLL" &&
      set "INCLUDE=%WATCOM%\H;%WATCOM%\H\OS2"
    )

  - if "%CONFIGURATION%"=="Debug" (
      set CMAKE_DEBUG_ARGS="-DPDCDEBUG=ON"
    ) else (
      set CMAKE_DEBUG_ARGS=""
    )

build_script:

  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build

  - cmake %CMAKE_TOOLCHAIN_ARGS% -G"%GENERATOR%" -DCMAKE_VERBOSE_MAKEFILE=TRUE
          -DCMAKE_BUILD_TYPE=%CONFIGURATION% 
          "-DCMAKE_INSTALL_PREFIX=%DIST_DIR%\%APPVEYOR_BUILD_WORKER_IMAGE%"
          -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% %CMAKE_DEBUG_ARGS% %CMAKE_ARGS%
          ..

    cmake --build . --config %CONFIGURATION% --target install

after_build:
  - cd %DIST_DIR%
  - 7z a -tzip %ARCHIVE%.zip "%APPVEYOR_BUILD_WORKER_IMAGE%"
  - certutil -hashfile %ARCHIVE%.zip MD5 > %ARCHIVE%.md5

artifacts:
  - path: dist\$(ARCHIVE).zip
  - path: dist\$(ARCHIVE).md5
