# Watcom Makefile for PDCurses - DOS
#
# Usage: wmake -f [path\]Makefile.wcc [DEBUG=Y] [WIDE=Y] [MODEL=c|h|l|m|s|f] [target]
#
# where target can be any of:
# [all|demos|pdcurses.lib|testcurs.exe...]

!ifndef MODEL
MODEL		= l
!endif

!ifdef %PDCURSES_SRCDIR
PDCURSES_SRCDIR	= $(%PDCURSES_SRCDIR)
!else
PDCURSES_SRCDIR	= ..
!endif

osdir		= $(PDCURSES_SRCDIR)/dosvga

TARGET		= dos

!ifeq MODEL f
CC		= wcc386
LTARGET		= dos4g
!else
CC		= wcc
LTARGET		= dos
!endif

CFLAGS		= -m$(MODEL)

!ifeq WIDE Y
CFLAGS		+= -DPDC_WIDE
!endif

!include $(PDCURSES_SRCDIR)/common/watcom.mif

$(LIBCURSES) : $(LIBOBJS) $(PDCOBJS)
	%write wccdos.lrf $(LIBOBJS) $(PDCOBJS)
	$(LIBEXE) $@ @wccdos.lrf
	-$(RM) wccdos.lrf
