# Watcom Makefile for PDCurses - Windows console
#
# Usage: wmake -f [path\]Makefile.wcc [DEBUG=Y] [WIDE=Y] [UTF8=Y]
#        [INFOEX=N] [target]
#
# where target can be any of:
# [all|demos|pdcurses.lib|testcurs.exe...]

!ifdef %PDCURSES_SRCDIR
PDCURSES_SRCDIR = $(%PDCURSES_SRCDIR)
!else
PDCURSES_SRCDIR = ..
!endif

osdir = wincon

TARGET = nt

LTARGET = nt

CFLAGS =

!ifeq INFOEX N
CFLAGS += -DHAVE_NO_INFOEX
!endif

!include $(PDCURSES_SRCDIR)/common/watcom.mif
